services:
  api:
    build:
      context: docker-api
      dockerfile: Dockerfile
      args:
        - IMAGE_NAME=docker-api
    image: ${IMAGE_NAME}
    ports:
      - 5000:4000
    depends_on:
      - db

  front:
    build:
      context: docker-front
      dockerfile: Dockerfile
      args:
        - IMAGE_NAME=docker-front
    image: ${IMAGE_NAME}
    ports:
    - 3000:80

  db:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=users