# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

# development:
#   <<: *default
#   database: db/development.sqlite3

development:
  adapter: postgresql
  pool: 5
  host: 3.80.47.206
  port: 5432
  encoding: unicode
  database: users
  username: docker
  password: docker

production:
  adapter: postgresql
  pool: 5
  host: 3.80.47.206
  port: 5432
  encoding: unicode
  database: users
  username: docker
  password: docker
