FROM postgres:15.1-alpine

LABEL author="Erick Obuya"
LABEL description="Postgres Image"
LABEL version="1.0"

ENV POSTGRES_DB users

ENV POSTGRES_PASSWORD docker
ENV POSTGRES_USER docker
# COPY world.sql /docker-entrypoint-initdb.d/